### ISSUE TITLE
Freenet

### ISSUE THREAD

**Issue by thej33k** [fazo96/tesina#1]
Se possibile aggiungi un riferimento a Freenet:

https://freenetproject.org/

http://en.wikipedia.org/wiki/Freenet

**Comment by fazo96** [comment]
Wow, non sapevo nemmeno dell'esistenza di questo progetto! Molto interessante!

Grazie prof.!

**Comment by fazo96** [comment]
ho aggiunto una sezione su Freenet nel commit 4a51a7340f031d00c9e6f1b09d46cb107992a1b7

Se ho tempo, la espanderò
